# File: .github/workflows/ci.yml
# Minimal, robust CI for Python matrix. Optional heavy extras are guarded by a step-level condition.

name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch: {}         # allow manual runs from the Actions tab

permissions:
  contents: read                # least-privilege token for checkout

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true      # auto-cancel older runs on the same branch

jobs:
  build:
    name: Python ${{ matrix.python-version }}
    runs-on: ubuntu-latest
    timeout-minutes: 25
    strategy:
      fail-fast: false
      matrix:
        python-version: [ "3.9", "3.10", "3.11" ]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: pip

      - name: Install dependencies (lenient)
        # Try requirements.txt; if it fails or does not exist, install the minimal set used by the README.
        run: |
          python -m pip install -U pip
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt || { echo "Falling back to minimal deps"; pip install numpy pandas matplotlib scikit-learn; }
          else
            pip install numpy pandas matplotlib scikit-learn
          fi

      - name: Install heavy extras (optional)
        # Toggle via Repository Settings → Actions → Variables → EXTRAS = true
        if: ${{ vars.EXTRAS == 'true' }}
        run: |
          sudo apt-get update
          sudo apt-get install -y gfortran libopenblas-dev liblapack-dev
          pip install healpy scipy shap lime qutip

      - name: Smoke test
        run: |
          python - <<'PY'
          import sys
          print("Python:", sys.version)
          for pkg in ("numpy","pandas","matplotlib","sklearn"):
              __import__(pkg)
          print("Smoke test OK")
          PY
