# File: .github/workflows/ci.yml
name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch: {}   # allow manual runs

permissions:
  contents: read          # least-privilege token

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 25
    strategy:
      fail-fast: false
      matrix:
        python-version: [ "3.9", "3.10", "3.11" ]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: pip

      - name: Install dependencies (lenient)
        run: |
          python -m pip install -U pip
          if [ -f requirements.txt ]; then
            # Try your pinned deps; if fail, fall back to a minimal set
            pip install -r requirements.txt || { echo "Falling back to minimal deps"; pip install numpy pandas matplotlib scikit-learn; }
          else
            pip install numpy pandas matplotlib scikit-learn
          fi

          # OPTIONAL: install heavy extras only if you set EXTRAS=true (Repo Settings → Actions → Variables)
          if [ "${{ vars.EXTRAS || 'false' }}" = "true" ]; then
            sudo apt-get update
            sudo apt-get install -y gfortran libopenblas-dev liblapack-dev
            pip install healpy scipy shap lime qutip
          fi

      - name: Smoke test
        run: |
          python - <<'PY'
          import sys
          print("Python:", sys.version)
          for pkg in ("numpy","pandas","matplotlib","sklearn"):
              __import__(pkg)
          print("Smoke test OK")
          PY
